# Site settings
title: prosa
email: prosa100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Ada Rosa. I am studying CS@UIUC.
  I build biomedical devices to help people live life to the fullest.
  I do research in LaValle's VR Lab. This is my blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prosa100.github.io" # the base hostname & protocol for your site
twitter_username: prosa100
github_username:  prosa100

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'prosa100'

# Build settings
markdown: kramdown
